### ISSUE TITLE
General TODO list:

### ISSUE THREAD

**Issue by egabancho** [inveniosoftware/invenio-saml#3]
- [ ] Find a way to build the docs: read the docs is missing one XML system library and the build fails. @egabancho 
- [ ] Explore better possibilities for the configuration, right now it might be too much. (Identify pain points) @egabancho 
- [ ] Improve documentation 💸 💸 💸 💸 
- [ ] Find a way to update the logging template with the corresponding links. @egabancho 
- [x]  Add debug logging to the default ACS handler to help with the development of the account info extractor. @egabancho 
- [x] Test loading from a file @mb-wali
- [x] Add explanation on how to disable user profile modifications 💸 
- [x] For the account info mappings make a default function to do a simple one to one mapping, more complicated things a function should be provided. @mb-wali
- [x] Verify if installation with and without OAuth client works, and if there are problems with the models (DB) find a way to solve them.
- [ ] **Release v1.0.0** 🚀 

---

- [ ] ~Extract common functions to the corresponding modules, Invenio-Accounts and Invenio-App mostly, i.e. `UserIdentity` or `get_safe_redirect_target`.~
- [ ] Test load config from server XML response
- [ ] Test IdP discovery reading from XML file
- [ ] Where to store data coming from the server, office number, phone, etc. user profile? remote account table?

**Comment by ntarocco** [comment]
🚀  Alpha release: https://github.com/inveniosoftware/invenio-saml/commit/676d20f53b9fda383f516a1e38a288a2b5851126

A new issue will be created with the remaining points to be addressed.
